BBPATH .= ":${LAYERDIR}"
BBFILES += "${LAYERDIR}/recipes-*/*/*.bb ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "iotdemo"
BBFILE_PATTERN_iotdemo = "^${LAYERDIR}/"
BBFILE_PRIORITY_iotdemo = "10"

LAYERDEPENDS_iotdemo = "core rauc raspberrypi"
LAYERSERIES_COMPAT_iotdemo = "scarthgap"